estimator: FasterRCNN
backbone: resnet50
num_classes: 64
task: object_detection
train:
  epochs: 30
  batch_size: 8
  accumulation_steps: 8
  log_frequency: 30
  dataset:
    name: ABGroceriesReal
    args:
      version: v3
      split: train
      target_label: drink_coffeebeans_kickinghorse
val:
  batch_size: 8
  dataset:
    name: ABGroceriesReal
    args:
      version: v3
      split: val
      target_label: drink_coffeebeans_kickinghorse
test:
  batch_size: 8
  dataset:
    name: ABGroceriesReal
    args:
      version: v3
      split: val
      target_label: drink_coffeebeans_kickinghorse
metrics:
  mAP:
    name: MeanAveragePrecisionAverageOverIOU
  mAPIOU50:
    name: MeanAveragePrecisionIOU50
  mAR:
    name: MeanAverageRecallAverageOverIOU
  APIOU50:
    name: AveragePrecisionIOU50
optimizer:
  name: Adam
  args:
    lr: 2.0e-5
pretrained: False
pretrained_backbone: True
synchronize_metrics: True
