estimator: FasterRCNN
backbone: resnet50
num_classes: 6
task: object_detection
train:
  epochs: 20
  batch_size: 6
  accumulation_steps: 8
  log_frequency: 30
  dataset:
    name: CocoDetection
    args:
      version: v3
      split: train
val:
  batch_size: 8
  dataset:
    name: CocoDetection
    args:
      version: v3
      split: val
test:
  batch_size: 8
  dataset:
    name: CocoDetection
    args:
      version: v3
      split: val
metrics:
  mean-average-precision:
    name: MeanAveragePrecisionAverageOverIOU
  mean-average-precision-iou50:
    name: MeanAveragePrecisionIOU50
  mean-average-recall:
    name: MeanAverageRecallAverageOverIOU
  average-precision-iou50:
    name: AveragePrecisionIOU50
optimizer:
  name: Adam
  args:
    lr: 2.0e-4
pretrained: False
pretrained_backbone: True
synchronize_metrics: True
