apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: train-on-unity-simulation-dataset-for-coco-cat-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.1, pipelines.kubeflow.org/pipeline_compilation_time: '2020-12-03T11:35:10.100801',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Train on Unity Simulation
      dataset for COCO-cat", "inputs": [{"default": "unitytechnologies/datasetinsights:latest",
      "name": "docker", "optional": true, "type": "String"}, {"default": "<unity-project-id>",
      "name": "project_id", "optional": true, "type": "String"}, {"default": "<unity-simulation-run-execution-id>",
      "name": "run_execution_id", "optional": true, "type": "String"}, {"default":
      "<unity-simulation-access-token>", "name": "access_token", "optional": true,
      "type": "String"}, {"default": "gs://thea-dev/data/coco_cat/train2017.zip",
      "name": "source_val_uri", "optional": true, "type": "String"}, {"default": "gs://thea-dev/data/coco_cat/annotations_trainval2017.zip",
      "name": "ann_uri", "optional": true, "type": "String"}, {"default": "datasetinsights/configs/faster_rcnn_coco_cat_synthetic.yaml",
      "name": "config", "optional": true, "type": "String"}, {"default": "gs://<bucket>/runs/yyyymmdd-hhmm",
      "name": "tb_log_dir", "optional": true, "type": "String"}, {"default": "gs://<bucket>/checkpoints/yyyymmdd-hhmm",
      "name": "checkpoint_dir", "optional": true, "type": "String"}, {"default": "100Gi",
      "name": "volume_size", "optional": true, "type": "String"}], "name": "Train
      on Unity Simulation dataset for COCO-cat"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.1}
spec:
  entrypoint: train-on-unity-simulation-dataset-for-coco-cat
  templates:
  - name: download
    container:
      args: ['--source-uri=usim://{{inputs.parameters.access_token}}@{{inputs.parameters.project_id}}/{{inputs.parameters.run_execution_id}}',
        --output=/data, --include-binary]
      command: [datasetinsights, download]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: access_token}
      - {name: docker}
      - {name: project_id}
      - {name: pvc-name}
      - {name: run_execution_id}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: download-2
    container:
      args: ['--source-uri={{inputs.parameters.source_val_uri}}', --output=/data,
        --include-binary]
      command: [datasetinsights, download]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: docker}
      - {name: pvc-name}
      - {name: source_val_uri}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: download-3
    container:
      args: ['--source-uri={{inputs.parameters.ann_uri}}', --output=/data, --include-binary]
      command: [datasetinsights, download]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: ann_uri}
      - {name: docker}
      - {name: pvc-name}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: evaluate
    container:
      args: ['--config={{inputs.parameters.config}}', '--checkpoint-file={{inputs.parameters.checkpoint_dir}}',
        --test-data=/data, '--tb-log-dir={{inputs.parameters.tb_log_dir}}', --kfp-log-dir=/kfp_logs,
        --kfp-ui-metadata-filename=kfp_ui_metadata.json, --kfp-metrics-filename=kfp_metrics.json]
      command: [datasetinsights, evaluate]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {nvidia.com/gpu: 1, memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: checkpoint_dir}
      - {name: config}
      - {name: docker}
      - {name: pvc-name}
      - {name: tb_log_dir}
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /kfp_logs/kfp_metrics.json}
      - {name: mlpipeline-ui-metadata, path: /kfp_logs/kfp_ui_metadata.json}
    nodeSelector: {cloud.google.com/gke-accelerator: nvidia-tesla-v100}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: pvc
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-pvc'
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: '{{inputs.parameters.volume_size}}'
    inputs:
      parameters:
      - {name: volume_size}
    outputs:
      parameters:
      - name: pvc-manifest
        valueFrom: {jsonPath: '{}'}
      - name: pvc-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: pvc-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
  - name: train
    container:
      args: ['--config={{inputs.parameters.config}}', --train-data=/data, --val-data=/data,
        '--tb-log-dir={{inputs.parameters.tb_log_dir}}', --kfp-log-dir=/kfp_logs,
        --kfp-ui-metadata-filename=kfp_ui_metadata.json, '--checkpoint-dir={{inputs.parameters.checkpoint_dir}}']
      command: [python, -m, torch.distributed.launch, --nproc_per_node=8, --use_env,
        datasetinsights, train]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {nvidia.com/gpu: 8, memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: checkpoint_dir}
      - {name: config}
      - {name: docker}
      - {name: pvc-name}
      - {name: tb_log_dir}
    outputs:
      artifacts:
      - {name: mlpipeline-ui-metadata, path: /kfp_logs/kfp_ui_metadata.json}
    nodeSelector: {cloud.google.com/gke-accelerator: nvidia-tesla-v100}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: train-on-unity-simulation-dataset-for-coco-cat
    inputs:
      parameters:
      - {name: access_token}
      - {name: ann_uri}
      - {name: checkpoint_dir}
      - {name: config}
      - {name: docker}
      - {name: project_id}
      - {name: run_execution_id}
      - {name: source_val_uri}
      - {name: tb_log_dir}
      - {name: volume_size}
    dag:
      tasks:
      - name: download
        template: download
        dependencies: [pvc]
        arguments:
          parameters:
          - {name: access_token, value: '{{inputs.parameters.access_token}}'}
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: project_id, value: '{{inputs.parameters.project_id}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
          - {name: run_execution_id, value: '{{inputs.parameters.run_execution_id}}'}
      - name: download-2
        template: download-2
        dependencies: [download, pvc]
        arguments:
          parameters:
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
          - {name: source_val_uri, value: '{{inputs.parameters.source_val_uri}}'}
      - name: download-3
        template: download-3
        dependencies: [download-2, pvc]
        arguments:
          parameters:
          - {name: ann_uri, value: '{{inputs.parameters.ann_uri}}'}
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
      - name: evaluate
        template: evaluate
        dependencies: [pvc, train]
        arguments:
          parameters:
          - {name: checkpoint_dir, value: '{{inputs.parameters.checkpoint_dir}}'}
          - {name: config, value: '{{inputs.parameters.config}}'}
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
          - {name: tb_log_dir, value: '{{inputs.parameters.tb_log_dir}}'}
      - name: pvc
        template: pvc
        arguments:
          parameters:
          - {name: volume_size, value: '{{inputs.parameters.volume_size}}'}
      - name: train
        template: train
        dependencies: [download-3, pvc]
        arguments:
          parameters:
          - {name: checkpoint_dir, value: '{{inputs.parameters.checkpoint_dir}}'}
          - {name: config, value: '{{inputs.parameters.config}}'}
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
          - {name: tb_log_dir, value: '{{inputs.parameters.tb_log_dir}}'}
  arguments:
    parameters:
    - {name: docker, value: 'unitytechnologies/datasetinsights:latest'}
    - {name: project_id, value: <unity-project-id>}
    - {name: run_execution_id, value: <unity-simulation-run-execution-id>}
    - {name: access_token, value: <unity-simulation-access-token>}
    - {name: source_val_uri, value: 'gs://thea-dev/data/coco_cat/train2017.zip'}
    - {name: ann_uri, value: 'gs://thea-dev/data/coco_cat/annotations_trainval2017.zip'}
    - {name: config, value: datasetinsights/configs/faster_rcnn_coco_cat_synthetic.yaml}
    - {name: tb_log_dir, value: 'gs://<bucket>/runs/yyyymmdd-hhmm'}
    - {name: checkpoint_dir, value: 'gs://<bucket>/checkpoints/yyyymmdd-hhmm'}
    - {name: volume_size, value: 100Gi}
  serviceAccountName: pipeline-runner
